(global-set-key (kbd "C-c C-c") 'mc/edit-lines)
(global-set-key (kbd "C-.") 'mc/mark-next-like-this)
(global-set-key (kbd "C-c C-g") 'rgrep)
(global-set-key (kbd "C-c C-m") 'mc/edit-lines)
(global-set-key (kbd "M-?") 'comment-or-uncomment-region)
(global-set-key (kbd "C-c C-w") 'insert-single-quotes)
(global-set-key (kbd "C-c C-q") 'insert-double-quotes)
(global-set-key (kbd "C-<S-down>") 'mc/mark-next-lines)
(global-set-key (kbd "C-M-g") 'toggle-fullscreen)
