;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        kill-region
        mc/mark-next-lines
        ))

(setq mc/cmds-to-run-once
      '(
        coffee-dedent-line-backspace
        orgtbl-self-insert-command
        ))
